### ISSUE TITLE
Product > Options >> useless select field

### ISSUE THREAD

**Issue by osworx** [arastta/arastta#137]
Whenever I open the product options (with already saved options), there is one select field too many at the bottom:
![a_1_0_8_product_options](https://cloud.githubusercontent.com/assets/1905204/8637392/d4dd093c-288f-11e5-9cc3-48be832f0abf.png)

**Comment by cuneytsenturk** [comment]
The option bring all item for User add new option item look here and User decide which item add in the option.
![product-option](https://cloud.githubusercontent.com/assets/10936547/8673010/e1bcfc18-2a3b-11e5-8be9-5af76b27105d.png)

Can you explain a little bit more? or  You can  take video this issue, Because I think something,
- Option name etc.

**Comment by osworx** [comment]
This field there makes no sense at least.
There are already the select fields above at each row - no need for an additional fields below the form which cannot be used - and will confuse everybody.
Beside, which selection what for should be made there ?
