### ISSUE TITLE
Gift Voucher expiry date

### ISSUE THREAD

**Issue by syntaxerror** [arastta/arastta#196]
Normally Gift Vouchers would not be valid forever, normal is like one year I believe.
Thus the Gift Vouchers would need a option for setting the expiry date.

**Comment by osworx** [comment]
From the legal department - valid for Austria for example( have to check for other EC-Countries): Gift Vouchers are valid for 30 years!
Starting with the date the voucher is created/bought.

**Comment by syntaxerror** [comment]
Normal seems to be 12 months in Ireland (EU), most less than 5 years: http://www.consumerhelp.ie/voucher-expiry

Amazon UK has 10 years: http://www.amazon.co.uk/gp/help/customer/display.html?nodeId=200272910

Normal for Norway and other Scandinavian countries is 6-12 months. For Norway, if no expiry day is set, it's valid for 3 years according to law ...

So expiry date is something the stores needs to be able to set (possibly per delivery country?).

**Comment by osworx** [comment]
Just for information: https://de.wikipedia.org/wiki/Gutschein (see also an article about: http://www.format.at/service/recht/ogh-gutscheine-30-jahre-338044)
**Austria**: if NO date is given, or a fact-base reason does **not exist**, are vouchers in Austria **valid for 30 years** (since 28th June 2012 by a descision of the high-court).
**Germany**: general 3 years, except for special reasons (e.g. a short-term visit of a theater).

**Comment by syntaxerror** [comment]
Closing this, added to ideas section instead:
https://arastta.org/ideas/idea/48-gift-voucher-expiry-date
