### ISSUE TITLE
Product filters don't work with SEO URL in frontend

### ISSUE THREAD

**Issue by syntaxerror** [arastta/arastta#386]
Seems like the product filters doesn't work in frontend when SEO URL is activated, but they works when it's disabled. Default template tested.

When a filter is applied in frontend through the module, and SEO URL is active, Arastta will just display:

> The requested site could not be found

This feature: https://arastta.org/docs/user-manual/catalog/filters

**Comment by hiperpixel** [comment]
There are two files that need to be changed for it to work, here's my solution:

in the file '/catalog/view/theme/default/template/module/filter.tpl'  replace line 37 from:
`location = '<?php echo $action; ?>&filter=' + filter.join(',');`
to:
`location = '<?php echo $action, (strpos($action, '?') === FALSE ? '?' : '&'); ?>filter=' + filter.join(',');`

and in file '/system/library/route.php' in the function 'parseNonSeoVariables' starting at line 384  the line that reads:
`$value = urlencode($value);`
should  be changed to :
`$value = $this->request->clean($value);`

This last one is necessary otherwise multiple filters will fail to show.

**Comment by syntaxerror** [comment]
@hiperpixel, could you make a PR for your solution?

**Comment by cuneytsenturk** [comment]
@hiperpixel Thank you your suggest.
