### ISSUE TITLE
1.3+ Update - TinyMCE isn't available to choose

### ISSUE THREAD

**Issue by syntaxerror** [arastta/arastta#444]
After updating to 1.3.0/1 TinyMCE isn't available to choose in settings or on admin user, only Summernote displaying.

To test you can install 1.2.7, go to "Extensions - View All ...", filter to display editors, they both shows up as disabled. Don't change anything. In settings both are still available to choose though.

Update to latest 1.3.1, go back to see the status of editors, you'll notice Summernote now is published while TinyMCE still is disabled. Publish TinyMCE (note that a lot of plugins is disabled in it too), then go to settings to choose editor - only Summernote displays ...

**Comment by cuneytsenturk** [comment]
> To test you can install 1.2.7, go to "Extensions - View All ...", filter to display editors, they both shows up as disabled. Don't change anything. In settings both are still available to choose though.

if you go to any extension page at Arastta 1.2.x, Discover feature that is added at Arastta 1.2.0 scans extension folders and adds extensions to the addon table so it makes these extensions' default status disable. 
Thus, TinyMCE seems as disabled so this process is normal.

 This happens due to the following line 
`$tinymce = $this->db->query("SELECT DISTINCT * FROM " . DB_PREFIX . "setting WHERE`code`= 'tinymce'");` 
https://github.com/arastta/arastta/commit/380b4cc7f31c489d3f6c7a02e469c4e5951f04fb#diff-a7f07d4164956baccff73136208ed902L261
