### ISSUE TITLE
Admin user named "Ada Bulut" after installation

### ISSUE THREAD

**Issue by JAY6390** [arastta/arastta#6]
Not exactly a huge issue, but still quite confusing. Would recommend something more generic such as "Admin User" as the name by default, or ask for the details upon installation

**Comment by denisdulici** [comment]
That was named as "John Doe" with OpenCart and we renamed with a female one with positive discrimination purpose. Being a non-English name maybe quite confusing, right. Must discuss this.

**Comment by JAY6390** [comment]
Yeah I understand what you mean but as an English native speaker it threw me a little :smile:

**Comment by denisdulici** [comment]
And as the default language of the software is English, having an English name should be preferable. Any suggestion as an English native speaker ;)

**Comment by OEA** [comment]
I can suggest Luke Skywalker :+1:

**Comment by JAY6390** [comment]
Ha great suggestion @OEASLAN !

**Comment by osworx** [comment]
Dart Vader - or how this guy is spelled ..

**Comment by denisdulici** [comment]
Menfolk.. Why not a lady :confused:

BTW, WP leaves it blank :smile:

**Comment by JAY6390** [comment]
Princess Leia then? :wink: I'd still rather see a field for first and second names, or auto-redirect to that page the first time the admin logs in. I find it a bit peculiar there are fields that are mandatory, but not in the installation - and while I can appreciate that's how OpenCart has it, I was under the assumption this project was to improve on OC significantly and not simply re-brand it with a few extra features

**Comment by osworx** [comment]
Because `'It's a real men world'.`
Okay back to topic: many years ago, before Joomla came out, I have made a fork of Mambo (from Joomla is made).
Each major release had a 'theme', for example version 2.x.z was published in the year of a round birthday of Mozart.
So I decided to name each minor version after a opera, like `La Traviatta`,  `Figaro` and so on.
And I explained a bit about that name in an extra readme.
Was funny .. but why not doing such?

**Comment by OEA** [comment]
I am a strict fan of Star Wars also I didn't see positive discrimination purpose :) So I can suggest Leia Organa(Skywalker) was the younger twin sister of Luke Skywalker. Also developers are happy when they see names about Star Wars :) If we talk about real world, I can suggest Emily, Emma, Elizabeth etc. You can see common names. 
http://en.wikipedia.org/wiki/List_of_most_popular_given_names

**Comment by denisdulici** [comment]
It is Jay, currently discussing the language tag/locale type with the translation team. Trying to normalise OpenCart.

I'm with adding a slider named like "Advanced" where it fades down once clicked and shows up such fields fields bellow the current ones.

In the first step, the database driver must be like this, currently MySQLi used.

**Comment by osworx** [comment]
`It is Jay, currently discussing the language tag/locale type with the translation team. Trying to normalise OpenCart.`
Interesting .. did not know that OpenCart has a 'translation team' .. must be very new.

**Comment by denisdulici** [comment]
Not OpenCart, [Arastta](http://arastta.org/community/groups/item/5-translation-team) :wink:

**Comment by osworx** [comment]
aja .. okay.
As already suggested per email, I would like to see the languages as other big(ger) projetcs still have.
In the way: `de-DE, or en-GB, en-US`
Joomla still use that since many years, as well others too.

Suggested such already many months ago at OC, but they do what they want.
Having this naming convention in my crowdin repo (OC translation v.2 project) and it is good.
Finally, does no matter which system will be used, it should be published!
Otherwise every shitty developer think he has to call his localized folder in another name.
Like the German translation where I have seen - beside the correct `de-DE` (since 2.x, before de_DE) - this: `German, german, de, germany`
And that makes no sense at all.

From my point of view: `xx-YY`

**Comment by doemech** [comment]
Why not ask the user for his name after the installation? You ask for the admin mail address anyway, so ask for a name :)

**Comment by inluxc** [comment]
+1

**Comment by denisdulici** [comment]
Changing admin name during installation is planned to be added into the Arastta 1.1 version.

**Comment by denisdulici** [comment]
Closing this issue, you're welcome to comment on #112
