### ISSUE TITLE
Composer install fails

### ISSUE THREAD

**Issue by degwebsolutions** [arastta/arastta#745]
Hi!

I've tried to install both master and 1.7 dev version on my dev server and look what composer returned:

`Loading composer repositories with package information
Updating dependencies (including require-dev)

  [Composer\Repository\RepositorySecurityException]
  The contents of https://packagist.org/p/provider-latest%240cbfb40ab72a881d21b70f78286d39cd72e3b0eb8704c13e79dc49624e549973.json do not match its signature. This could indicate a man-in-the-middle attack. Try running composer again a
  nd report this if you think it is a mistake.`

**Comment by syntaxerror** [comment]
Why would you do that, instead of using the latest stable?
https://github.com/arastta/arastta/releases

Anyhow, this is most likely a Composer or Packagist issue, and not an Arastta issue.
https://github.com/composer/composer/issues

Packagist had some issues lately:
https://twitter.com/packagist/status/953257504565334016
